"use client";
import { useState } from "react";
import styles from "./page.module.css";
type Kind = "text" | "rectangle" | "ellipse" | "image";
type Item = { id: string; kind: Kind; x: number; y: number; width: number; height: number; properties: Record<string, string> };
const defaults: Record<Kind, Record<string, string>> = { text: { content: "Texto", color: "#111827" }, rectangle: { fill: "#2563eb" }, ellipse: { fill: "#f97316" }, image: { src: "https://placehold.co/320x200/e5e7eb/374151?text=Imagem" } };
export default function Home() {
  const [items, setItems] = useState<Item[]>([]); const [selected, setSelected] = useState<string | null>(null); const current = items.find(i => i.id === selected);
  const add = (kind: Kind) => { const item = { id: crypto.randomUUID(), kind, x: 80 + items.length * 16, y: 80 + items.length * 16, width: kind === "text" ? 220 : 180, height: kind === "text" ? 56 : 120, properties: defaults[kind] }; setItems([...items, item]); setSelected(item.id); };
  const update = (id: string, change: Partial<Item>) => setItems(items.map(i => i.id === id ? { ...i, ...change } : i));
  return <main className={styles.editor}><header><strong>Zeta Design</strong><span>Projeto sem título</span><button>Salvar</button></header><aside className={styles.toolbar}><b>Elementos</b>{(["text","rectangle","ellipse","image"] as Kind[]).map(kind => <button key={kind} onClick={() => add(kind)}>+ {kind}</button>)}</aside><section className={styles.workspace}><div className={styles.canvas} onClick={() => setSelected(null)}>{items.map(item => <div key={item.id} onClick={e => {e.stopPropagation();setSelected(item.id)}} className={`${styles.element} ${selected === item.id ? styles.selected : ""} ${styles[item.kind]}`} style={{left:item.x,top:item.y,width:item.width,height:item.height,background:item.kind === "image" ? undefined : item.properties.fill}}>{item.kind === "text" && <span style={{color:item.properties.color}}>{item.properties.content}</span>}{item.kind === "image" && <img src={item.properties.src} alt="Imagem" />}</div>)}</div></section><aside className={styles.properties}><b>Propriedades</b>{!current ? <p>Selecione um elemento</p> : <>{(["x","y","width","height"] as const).map(field => <label key={field}>{field}<input type="number" value={current[field]} onChange={e => update(current.id,{[field]:Number(e.target.value)})}/></label>)}{current.kind === "text" && <label>Texto<input value={current.properties.content} onChange={e => update(current.id,{properties:{...current.properties,content:e.target.value}})}/></label>}<label>Cor<input type="color" value={current.properties.fill || current.properties.color} onChange={e => update(current.id,{properties:{...current.properties,[current.kind === "text" ? "color":"fill"]:e.target.value}})}/></label><button onClick={() => {setItems(items.filter(i => i.id !== current.id));setSelected(null)}}>Remover</button></>}</aside></main>;
}
